# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vAkdFaX1SmJOj4Ghas_3CqUKO-MWwGyP
"""

from flask import Flask, render_template, request

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/predict', methods=['GET', 'POST'])
def predict():
    if request.method == 'POST':
        age = int(request.form['age'])
        sex = int(request.form['sex'])
        bp = int(request.form['bp'])
        cholesterol = int(request.form['cholesterol'])
        na_to_k = float(request.form['na_to_k'])

        # TODO: Add your prediction code here

        return render_template('result.html', drug=prediction)
    else:
        return render_template('predict.html')

if __name__ == '__main__':
    app.run(debug=True)